# Generated by Django 4.2.27 on 2025-12-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='has_rainbow_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='park',
            name='pma_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='park',
            name='rainbow_sign_locations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
