# Generated by Django 4.2.27 on 2025-12-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_park_has_rainbow_sign_park_pma_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sign_type', models.CharField(default='RAINBOW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='parks.park')),
            ],
            options={
                'ordering': ['park__name'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='sign',
            field=models.ForeignKey(blank=True, help_text='Optional: specific sign visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='parks.sign'),
        ),
    ]
