# Generated by Django 4.2.27 on 2025-12-15 07:42

import json
from django.db import migrations


def populate_signs(apps, schema_editor):
    """Create Sign records from existing rainbow_sign_locations data."""
    Park = apps.get_model('parks', 'Park')
    Sign = apps.get_model('parks', 'Sign')

    for park in Park.objects.filter(rainbow_sign_locations__isnull=False).exclude(rainbow_sign_locations=''):
        try:
            locations = json.loads(park.rainbow_sign_locations)
            for coords in locations:
                if len(coords) >= 2:
                    # coords is [longitude, latitude]
                    Sign.objects.create(
                        park=park,
                        longitude=coords[0],
                        latitude=coords[1],
                        sign_type='RAINBOW'
                    )
        except (json.JSONDecodeError, TypeError):
            continue


def reverse_populate_signs(apps, schema_editor):
    """Remove all Sign records (reverse migration)."""
    Sign = apps.get_model('parks', 'Sign')
    Sign.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_add_sign_model'),
    ]

    operations = [
        migrations.RunPython(populate_signs, reverse_populate_signs),
    ]
